__WHAT_PATH = './images/whats/'
WHAT_PICTURES = [
        {'name': 'Соль', 'src': f'{__WHAT_PATH}(1).png'},
        {'name': 'Душ', 'src': f'{__WHAT_PATH}(2).png'},
        {'name': 'Лук', 'src': f'{__WHAT_PATH}(3).png'},
        {'name': 'Цепь', 'src': f'{__WHAT_PATH}(4).png'},
        {'name': 'Куб', 'src': f'{__WHAT_PATH}(5).png'},
        {'name': 'Рог', 'src': f'{__WHAT_PATH}(7).png'},
        {'name': 'Люк', 'src': f'{__WHAT_PATH}(8).png'},
        {'name': 'Зал', 'src': f'{__WHAT_PATH}(9).png'},
        {'name': 'Руль', 'src': f'{__WHAT_PATH}(10).png'},

        {'name': 'Семь', 'src': f'{__WHAT_PATH}(11).png'},
        {'name': 'Ком', 'src': f'{__WHAT_PATH}(12).png'},
        {'name': 'Мяч', 'src': f'{__WHAT_PATH}(13).png'},
        {'name': 'Суп', 'src': f'{__WHAT_PATH}(14).png'},
        {'name': 'Пуф', 'src': f'{__WHAT_PATH}(15).png'},
        {'name': 'Мох', 'src': f'{__WHAT_PATH}(16).png'},
        {'name': 'Мак', 'src': f'{__WHAT_PATH}(17).png'},
        {'name': 'Дом', 'src': f'{__WHAT_PATH}(18).png'},
        {'name': 'Сок', 'src': f'{__WHAT_PATH}(19).png'},
        {'name': 'Дуб', 'src': f'{__WHAT_PATH}(20).png'},

        {'name': 'Мёд', 'src': f'{__WHAT_PATH}(21).png'},
        {'name': 'Дым', 'src': f'{__WHAT_PATH}(22).png'},
        {'name': 'Фен', 'src': f'{__WHAT_PATH}(23).png'},
        {'name': 'Бак', 'src': f'{__WHAT_PATH}(24).png'},
        {'name': 'Лук', 'src': f'{__WHAT_PATH}(25).png'},
        {'name': 'Сыр', 'src': f'{__WHAT_PATH}(26).png'},
        {'name': 'Пень', 'src': f'{__WHAT_PATH}(27).png'},
        {'name': 'Нож', 'src': f'{__WHAT_PATH}(28).png'},
        {'name': 'Чай', 'src': f'{__WHAT_PATH}(29).png'},
        {'name': 'Ель', 'src': f'{__WHAT_PATH}(30).png'},

        {'name': 'Таз', 'src': f'{__WHAT_PATH}(31).png'},
        {'name': 'Лёд', 'src': f'{__WHAT_PATH}(32).png'},
        {'name': 'Меч', 'src': f'{__WHAT_PATH}(33).png'},
        {'name': 'Шар', 'src': f'{__WHAT_PATH}(34).png'},
        {'name': 'Лак', 'src': f'{__WHAT_PATH}(35).png'},
        {'name': 'Рис', 'src': f'{__WHAT_PATH}(36).png'},
        {'name': 'Лён', 'src': f'{__WHAT_PATH}(37).png'},
        {'name': 'Щит', 'src': f'{__WHAT_PATH}(38).png'},
        {'name': 'Чум', 'src': f'{__WHAT_PATH}(39).png'},
        {'name': 'Мел', 'src': f'{__WHAT_PATH}(40).png'},
    ]

__WHO_PATH = './images/whos/'
WHO_PICTURES = [
        {'name': 'Кот', 'src': f'{__WHO_PATH}(1).png'},
        {'name': 'Жук', 'src': f'{__WHO_PATH}(2).png'},
        {'name': 'Сом', 'src': f'{__WHO_PATH}(3).png'},
        {'name': 'Конь', 'src': f'{__WHO_PATH}(4).png'},
        {'name': 'Дед', 'src': f'{__WHO_PATH}(5).png'},
        {'name': 'Лось', 'src': f'{__WHO_PATH}(6).png'},
        {'name': 'Мышь', 'src': f'{__WHO_PATH}(7).png'},
        {'name': 'Лев', 'src': f'{__WHO_PATH}(8).png'},
        {'name': 'Рысь', 'src': f'{__WHO_PATH}(9).png'},
        {'name': 'Рак', 'src': f'{__WHO_PATH}(10).png'},

        {'name': 'Пёс', 'src': f'{__WHO_PATH}(11).png'},
        {'name': 'Чиж', 'src': f'{__WHO_PATH}(12).png'},
        {'name': 'Царь', 'src': f'{__WHO_PATH}(13).png'},
        {'name': 'Маг', 'src': f'{__WHO_PATH}(15).png'},
        {'name': 'Шут', 'src': f'{__WHO_PATH}(16).png'},
        {'name': 'Бык', 'src': f'{__WHO_PATH}(17).png'},
        {'name': 'Кит', 'src': f'{__WHO_PATH}(18).png'},
        {'name': 'Лис', 'src': f'{__WHO_PATH}(19).png'},
        {'name': 'Лещ', 'src': f'{__WHO_PATH}(20).png'},
        {'name': 'Гусь', 'src': f'{__WHO_PATH}(21).png'},
    ]