"""v0001

Revision ID: 262fa75bf562
Revises: 
Create Date: 2024-10-11 21:44:20.170464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262fa75bf562'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('imagefeeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('processed_image', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagefeeds_id'), 'imagefeeds', ['id'], unique=False)
    op.create_index(op.f('ix_imagefeeds_user_id'), 'imagefeeds', ['user_id'], unique=False)
    op.create_table('detectedobjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('image_feed_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['image_feed_id'], ['imagefeeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detectedobjects_id'), 'detectedobjects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detectedobjects_id'), table_name='detectedobjects')
    op.drop_table('detectedobjects')
    op.drop_index(op.f('ix_imagefeeds_user_id'), table_name='imagefeeds')
    op.drop_index(op.f('ix_imagefeeds_id'), table_name='imagefeeds')
    op.drop_table('imagefeeds')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
