# Generated by Django 5.1.2 on 2024-10-23 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_id',
            new_name='author',
        ),
    ]
